FROM cnn_monai_1.3_inference

# Copy necessary files
COPY models/* ./models/
COPY app.py ./
COPY app_loadrun_models.py ./
COPY classifier/preprocessing.py ./classifier/
COPY templates/* ./templates/

# Set default environment variables
ENV PORT=5000 WORKERS=1 THREADS=1

EXPOSE $PORT
CMD sh -c "gunicorn -w $WORKERS --threads $THREADS --bind 0.0.0.0:$PORT app:app"
