name: ml_class_monai_py3.11

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy
    - pandas
    - pydicom
    - scikit-learn
    - scikit-build
    - matplotlib
    - seaborn
    - itk
    - pdfkit
    - yattag
    - boto3
    - torch
    - tensorboard
    - tqdm
    - torchvision
    - monai==1.3.0
